#!/bin/bash
#SBATCH -A rrg-pmyers-ad_cpu
#SBATCH --time=00:04:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=350
#SBATCH --mail-type=ALL
#SBATCH --mail-user=zwhincup@ualberta.ca

/project/6007519/zwhincup/TempestEnv/tempestextremes-master/bin/DetectNodes --in_data "/project/6007519/ANHA4-I/ATMFORCING/ERA5/Ready/NEMO_ERA5_mslp_y2001.nc" --out "/project/6007519/zwhincup/TempestOutput/ERA5/DetectNodesOutput/2001_Lab_Candidates" --searchbymin msl --closedcontourcmd "msl,200.0,6.0,0" --mergedist 6.0 --outputcmd "msl,min,0" --latname "latitude" --lonname "longitude" --minlat 49.4 --maxlat 68.8 --minlon 290.5 --maxlon 324.0 --timefilter "....-..-.. (00|03|06|09|12|15|18|21):00:00" --out_header


