#!/bin/bash
#SBATCH -A rrg-pmyers-ad_cpu
#SBATCH --time=00:00:20
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=250
#SBATCH --mail-type=ALL
#SBATCH --mail-user=zwhincup@ualberta.ca

/project/6007519/zwhincup/TempestEnv/tempestextremes-master/bin/StitchNodes --in "/project/6007519/zwhincup/TempestOutput/ERA5/DetectNodesOutput/2001_Lab_Candidates" --out "/project/6007519/zwhincup/TempestOutput/ERA5/StitchNodesOutput/2001_ERA5_Lab_Candidates.csv" --range 6.0 --mintime "48h" --maxgap 18h --min_endpoint_dist 6.0 --out_file_format "csv" 
#--threshold lat,>,49.4;lon,>,290.5;lat,<,69;lon,<,324"

# range: maximum distance btwn candidates on a path, 6 great-circle degrees
# mintime: min duration of feature, 48 hours
# maxgap: max number of allowed missing points between nearby candidates to still consider them as the same path, 18h
# min_endpoint_dist: minimum distance btwn first and last points on a path (to exclude stationary features), 6 great-circle degrees
